# Generated by Django 5.2 on 2025-05-04 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.IntegerField()),
                ('issue_date', models.DateField(auto_now=True)),
                ('issue_time', models.TimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('birth_wilaya', models.CharField(max_length=100)),
                ('birth_commune', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('birth_number', models.CharField(max_length=15, unique=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('registration_date', models.DateField(auto_now=True)),
                ('registration_time', models.TimeField(auto_now=True)),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('rh', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('birth_number', models.CharField(max_length=15, unique=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_records', to='users.hospital')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.IntegerField()),
                ('issue_date', models.DateField(auto_now=True)),
                ('issue_time', models.TimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('death_time', models.TimeField()),
                ('birth_wilaya', models.CharField(max_length=100)),
                ('birth_commune', models.CharField(max_length=100)),
                ('death_wilaya', models.CharField(max_length=100)),
                ('death_commune', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('birth_number', models.CharField(max_length=15, unique=True)),
                ('death_number', models.CharField(max_length=15, unique=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('death_time', models.TimeField()),
                ('registration_date', models.DateField(auto_now=True)),
                ('registration_time', models.TimeField(auto_now=True)),
                ('death_wilaya', models.CharField(max_length=100)),
                ('death_commune', models.CharField(max_length=100)),
                ('birth_wilaya', models.CharField(max_length=100)),
                ('birth_commune', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('death_cause', models.CharField(max_length=255, null=True)),
                ('rh', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(default=0)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('birth_number', models.CharField(max_length=15, unique=True)),
                ('death_number', models.CharField(max_length=15, unique=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_records', to='users.hospital')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
