# Generated by Django 5.2 on 2025-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='certificate_number',
            field=models.CharField(),
        ),
    ]
