# Generated by Django 5.2 on 2025-04-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_birthrecord_user_deathrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthrecord',
            name='nuber_of_birth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='nuber_of_birth',
            field=models.IntegerField(null=True),
        ),
    ]
