# Generated by Django 5.2 on 2025-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_birthrecord_nuber_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathrecord',
            name='death_cause',
            field=models.CharField(null=True),
        ),
    ]
