# Generated by Django 5.2 on 2025-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_birthcertificateupdaterequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathrecord',
            name='death_type',
            field=models.CharField(choices=[('natural', 'Natural cause'), ('violent', 'Violent cause'), ('undetermined', 'Undetermined cause')], default='natural', max_length=30),
        ),
    ]
