# Generated by Django 5.2 on 2025-05-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_deathrecord_hospital'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthrecord',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_records', to='users.hospital'),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_records', to='users.hospital'),
        ),
    ]
