# Generated by Django 5.2 on 2025-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_birthrecord_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
