# Generated by Django 5.2 on 2025-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_birthrecord_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='birth_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='deathcertificate',
            name='birth_number',
            field=models.IntegerField(unique=True),
        ),
    ]
