# Generated by Django 5.2 on 2025-05-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_burialpermit'),
        ('users', '0002_alter_userinfo_organization_court_userinfo_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificateupdaterequest',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.court'),
        ),
    ]
