# Generated by Django 5.2 on 2025-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_birthcertificate_birth_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificate',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
    ]
