# Generated by Django 5.2 on 2025-05-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_birthcertificateupdaterequest_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='burialpermit',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.deathrecord'),
        ),
    ]
